SIM = icarus
TOPLEVEL_LANG = verilog
TOPLEVEL = systolicArray
COCOTB_TEST_MODULES = test_array
VERILOG_SOURCES = $(shell pwd)/../rtl/array/pe.v $(shell pwd)/../rtl/array/systolicArray.v

include $(shell cocotb-config --makefiles)/Makefile.sim