SIM = icarus
TOPLEVEL_LANG = verilog
TOPLEVEL = processingElement
COCOTB_TEST_MODULES = test_pe
VERILOG_SOURCES = $(shell pwd)/../rtl/array/pe.v

include $(shell cocotb-config --makefiles)/Makefile.sim